### ISSUE TITLE
簡轉繁錯誤 "才"不需轉換成"纔"

### ISSUE THREAD

**Issue by ag2s20150909** [liuyueyi/quick-chinese-transfer#1]
https://github.com/gedoor/legado/issues/980
簡轉繁錯誤 "才"不需轉換成"纔"，保持原來的"才"字才是正確的。纔字幾乎無人使用。

**Comment by liuyueyi** [comment]
香港/台湾繁体转简体时链路有问题，已修复， 0.2.0 版本已修复
