### ISSUE TITLE
繁转简：特=>特特

### ISSUE THREAD

**Issue by iyhkhtrk** [liuyueyi/quick-chinese-transfer#10]

**Comment by liuyueyi** [comment]
未复现

**Comment by liuyueyi** [comment]
辛苦给下复现的case

**Comment by iyhkhtrk** [comment]
重试了一下发现是：
洛哈特=>洛哈特特
另外发现：
人鬼情未了=>第六感生死戀

**Comment by liuyueyi** [comment]
人鬼情未了=>第六感生死戀  
这个属于翻译问题，台湾翻译的死《第六感生死戀 》

**Comment by iyhkhtrk** [comment]
> 人鬼情未了=>第六感生死戀 这个属于翻译问题，台湾翻译的死《第六感生死戀 》

人鬼情未了在繁转简会变成第六感生死戀，在简转繁还是人鬼情未了

**Comment by liuyueyi** [comment]
> > 人鬼情未了=>第六感生死戀 这个属于翻译问题，台湾翻译的死《第六感生死戀 》
> 
> 人鬼情未了在繁转简会变成第六感生死戀，在简转繁还是人鬼情未了

**Comment by liuyueyi** [comment]
> > 人鬼情未了=>第六感生死戀 这个属于翻译问题，台湾翻译的死《第六感生死戀 》
> 
> 人鬼情未了在繁转简会变成第六感生死戀，在简转繁还是人鬼情未了

收到，待处理
