### ISSUE TITLE
繁转简： 先進 -> 先进

### ISSUE THREAD

**Issue by Xwite** [liuyueyi/quick-chinese-transfer#19]
refs https://github.com/gedoor/legado/issues/3723

https://github.com/liuyueyi/quick-chinese-transfer/blob/481f9c2c82a9d7a5f67b2275d293f281dca062a2/transfer-core/src/main/resources/tc/t2s.txt#L1135

繁转简
https://www.zdic.net/hans/先進
先進 -> 先进

**Comment by Xwite** [comment]
Ref https://github.com/gedoor/legado/issues/3723

**Comment by liuyueyi** [comment]
fixed
